### ISSUE TITLE
README should mention how we create the snapshots

### ISSUE THREAD

**Issue by mathieujobin** [levinmr/rspec-snapshot#17]
do they need to be manually crafted?
can we generate them from an initial test run ? 
I'm not seeing anything that suggest how should one begin?!

thanks

**Comment by ufo2mstar** [comment]
@mathieujobin Yes, documentation should definitely be improved, and so should the features, because snapshot testing is a powerful idea! but lacks support across languages other than JS.

What I found to work was adding this to the top of your `./spec/spec_helper.rb` or equivalent
```ruby
require "rspec/snapshot"

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
```

and giving the filename of your snapshot in your `expect` call

```ruby
it 'should match shapshot' do
...
  expect(result).to match_snapshot 'shapshot_file_name'
...
end
```

which should create a `__snapshots__/shapshot_file_name.snap` file (or you can configure the output from a relative to your spec file path to a more fixed path, based on [this config](https://github.com/yesmeck/rspec-snapshot#configration)

```ruby
RSpec.configure do |config|
  # The default setting is `:relative`, which means snapshots will be generate to
  # the relative path of the spec file.
  config.snapshot_dir = "spec/fixtures/snapshots"
end
```

**Comment by levinmr** [comment]
Documentation improved in version 2.0.0 release
